version: '3'

services:
  shared_rabbitmq:
    container_name: medine-php_ddd_skeleton-rabbitmq
    image: 'rabbitmq:3.7-management'
    restart: unless-stopped
    ports:
      - 5630:5672
      - 8090:15672
    environment:
      - RABBITMQ_DEFAULT_USER=medine
      - RABBITMQ_DEFAULT_PASS=medine03

  todo_mysql:
    container_name: medine-php_ddd_skeleton-todo-mysql
    image: mysql:8.0
    ports:
      - 3360:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent" ]
      interval: 2s
      timeout: 10s
      retries: 10
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  todo_backend_php:
    container_name: medine-php_ddd_skeleton-todo_backend-php
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
      - "9040:9001"
    volumes:
      - .:/app:delegated
    depends_on:
      - shared_rabbitmq
    command: symfony serve --dir=apps/todo/backend/public --port=8040 --force-php-discovery
