tasks_put:
  path: /tasks/{id}
  controller: Medine\Apps\Todo\Backend\Controller\Tasks\TasksPutController
  methods: [ PUT ]

tasks_get:
  path: /tasks
  controller: Medine\Apps\Todo\Backend\Controller\Tasks\TasksGetController
  methods: [ GET ]