tasks_post:
  path: /tasks
  controller: Medine\Apps\Todo\Backend\Controller\Tasks\TasksPostController
  methods: [ POST ]

task_get:
  path: /tasks/{id}
  controller: Medine\Apps\Todo\Backend\Controller\Tasks\TaskGetController
  methods: [ GET ]

tasks_put:
  path: /tasks/{id}
  controller: Medine\Apps\Todo\Backend\Controller\Tasks\TasksPutController
  methods: [ PUT ]

tasks_get:
  path: /tasks
  controller: Medine\Apps\Todo\Backend\Controller\Tasks\TasksGetController
  methods: [ GET ]