#imports:
#  - { resource: ../../../../src/Todo/Shared/Infrastructure/Symfony/DependencyInjection/todo_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Controllers
  Medine\Apps\Todo\Backend\Controller\:
    resource: '../src/Controller'
    tags: [ 'controller.service_arguments' ]