#imports:
#  - { resource: ../../../../src/Todo/Shared/Infrastructure/Symfony/DependencyInjection/todo_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true

  # Controllers
  Medine\Apps\Todo\Backend\Controller\:
    resource: '../src/Controller'
    tags: [ 'controller.service_arguments' ]

  # Wire
  Medine\Shared\:
    resource: '../../../../src/Shared'

  Medine\Todo\:
    resource: '../../../../src/Todo'

  # -- TAGGING --
  Medine\Shared\Infrastructure\Symfony\AddJsonBodyToRequestListener:
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }