framework:
  test: true

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Medine\Tests\:
    resource: '../../../../tests'

  # Instance selector
  Medine\Shared\Domain\RandomNumberGenerator: '@Medine\Tests\Shared\Infrastructure\PhpStaticNumberGenerator'
  #Medine\Shared\Domain\Bus\Event\EventBus: '@Medine\Shared\Infrastructure\Bus\Event\InMemory\InMemorySymfonyEventBus'