services:
  # Databases
  Doctrine\ORM\EntityManager:
    factory: [ Medine\Todo\Shared\Infrastructure\Doctrine\TodoEntityManagerFactory, create ]
    arguments:
      - driver: '%env(TODO_DATABASE_DRIVER)%'
        host: '%env(TODO_DATABASE_HOST)%'
        port: '%env(TODO_DATABASE_PORT)%'
        dbname: '%env(TODO_DATABASE_NAME)%'
        user: '%env(TODO_DATABASE_USER)%'
        password: '%env(TODO_DATABASE_PASSWORD)%'
      - '%env(APP_ENV)%'
    tags:
      - { name: medine.database_connection }
    public: true


  # Courses
#  Medine\Todo\Courses\Domain\CourseRepository: '@Medine\Todo\Courses\Infrastructure\Persistence\DoctrineCourseRepository'